# Generated by Django 4.2.7 on 2024-07-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='note',
            new_name='notes',
        ),
    ]
